name: build_docs.yml
on:
  push:
    branches:
      - main
      - develop
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop repository
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - name: Checkout gh-pages repository
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: git branch -d gh-pages
      
      
